### ISSUE TITLE
platform.short_name and instrument.short_name cannot be empty

### ISSUE THREAD

**Issue by akorosov** [nansencenter/django-geo-spaas#1]
platform.short_name and instrument.short_name are used as natural_key in Source and cannot be empty.
But for level-4 data the short_names are empty because higher level GCMD platform and GCMD instrument must be used (e.g. ACTIVE REMOTE SENSING).
So far a hack is introduced in Nansat for GLOBCURRENT  data: mapper_opendap_globcurrent sets instrument and platform to Jason-1.

**Comment by mortenwh** [comment]
I suggest to add all "super-fields" of shortname to the `natural_key` methods and the `__str__` methods in the vocabularies to solve the problem with empty fields.

**Comment by mortenwh** [comment]
Note that the current search form only allows single entries of parameters, platforms and instruments. If we want to be able to search, e.g., several parameters, we need to change the filtering in the render method `viewer.views.IndexView.render`

**Comment by akorosov** [comment]
geospaas.catalog.models.Source

defines natural_key()
which uses short_name of insterument and platform.
But sometimes short_name can be empty. E.g.
[('Category', 'Earth Remote Sensing Instruments'),
              ('Class', ''),
              ('Type', ''),
              ('Subtype', ''),
              ('Short_Name', ''),
              ('Long_Name', '')]
In that case natural key is ambigous and Django fails.

### Solution 1
Add all fields to natural key: Category, Class, etc

### Solution 2 
Remove natural_key()
Question: Do we need this natural key at all?
https://docs.djangoproject.com/en/3.0/topics/serialization/#natural-keys

### Solution 3
Replace ForeingKey with ManyToMany relatiuonship from Dataset to Source. That is complicated
as it requires changing Nansat.

**Comment by aanersc** [comment]
@akorosov 
Dear Anton, please review the third test as well. I have modified the tests and return the fixture to their original state based on your comments.

**Comment by akorosov** [comment]
Closed in #80 by removing natural_key from several models in vocabularies.
