### ISSUE TITLE
partial-lentgh link instead of full-length link

### ISSUE THREAD

**Issue by aanersc** [nansencenter/django-geo-spaas#113]
urlize function must have larger number of input characters in the templates of django.

This only needs modification of django templating file.

**Comment by aperrin66** [comment]
#114 did not solve the problem.

For example, scihub URLs are still partially "urlized": the full URL is displayed, but only the following part is a link:
**https://scihub.copernicus.eu/apihub/odata/v1/Products(**

**Comment by akorosov** [comment]
There is no need in creating links in the base viewer. This functionality will anyway be overridden by child applications. Work here should be stopped.
