### ISSUE TITLE
"overlaps" filtering should be used instead of "intersects" filtering of spatial search

### ISSUE THREAD

**Issue by aanersc** [nansencenter/django-geo-spaas#123]
Here in this line of filtering which is used for spatial filtering by user, the user wants to see all the datasets that are inside or have some overlap with the border of his/her desired region. When we use  **intersects**, it only shows the datasets that have intersect with desired region, not the ones that are completely inside the desired region of the user. The user want the ones that are _**completely inside**_ the desired region as well.

It means we have change the filtering verb from "intersects" to "overlaps" for this line:
https://github.com/nansencenter/django-geo-spaas/blob/f88cec284af814dcca12ba73f67a328296936615/geospaas/base_viewer/forms.py#L46

Which means this line should be something like this:
`python
geographic_location__geometry__overlaps=self.cleaned_data['polygon'])
`

**Comment by aanersc** [comment]
@akorosov @aperrin66 
Please provide your feedback regarding this issue, individually.

**Comment by aperrin66** [comment]
Thanks for paying attention to this detail, but actually, it's the other way around: 
- `intersects` is true id the intersection of two geometries is not empty. This includes the case where one geometry contains the other
- `overlaps` is true if the geometries intersect and one does not contain the other.

This is confirmed by the documentation from PostGIS: http://postgis.net/docs/ST_Intersects.html and http://postgis.net/docs/ST_Overlaps.html, and by the documentation of Spatialite: https://www.gaia-gis.it/spatialite-2.0/spatialite2_sql.html.

**Comment by aanersc** [comment]
@aperrin66 
I have the docs. Yes, intersect is more comprehesive than the ovrelap. But why the user do not see the datasets that are completely inside the desired location?
Let me show you an example:
Here I have selected a small region for showing the datasets, it will show me some of the datasets:
![image](https://user-images.githubusercontent.com/62345618/88149026-c7f45900-cbff-11ea-9507-6d0e4210652d.png)

And then in a larger region(but at the same location), I search again with larger one:
 
![image](https://user-images.githubusercontent.com/62345618/88148914-99767e00-cbff-11ea-8f41-54f2efc84d4c.png)

And the result is something like this:
![image](https://user-images.githubusercontent.com/62345618/88148938-a6936d00-cbff-11ea-9a7d-f5e4880e8b6b.png)

It only shows the ones that are in intersection of the **_border_** of the datasets

**Comment by aanersc** [comment]
Is there any inconsistency between the **showing** and **filtering** the datasets?

**Comment by aperrin66** [comment]
This is because only the results in the current page are displayed.
