### ISSUE TITLE
Dataset that ends with exaclty the begin time of search time should not be displayed in viewer

### ISSUE THREAD

**Issue by aanersc** [nansencenter/django-geo-spaas#143]
Following my discussion with @aperrin66  in one of the PRs of metanorm. The last time of time must also be excluded in 
https://github.com/nansencenter/django-geo-spaas/blob/43fbe47787c78984adba730359c1f89343cba262/geospaas/base_viewer/forms.py#L31

**Comment by aperrin66** [comment]
The condition is `lt`, not `lte`, so `t_0` is already excluded.
What exactly do you want to do here?

**Comment by aanersc** [comment]
`lte ` should be there instead of `lt`

**Comment by aperrin66** [comment]
Oh right, it's an exclusion condition, my bad.
