### ISSUE TITLE
Use 100% for table height

### ISSUE THREAD

**Issue by akorosov** [nansencenter/django-geo-spaas#150]
https://github.com/nansencenter/django-geo-spaas/blob/70c993339c5db28386cff66ffd885c002f0c573c/geospaas/base_viewer/static/base_viewer/styles.css#L19

replace    `max-height: 620px;` with `max-height: 100%;`

**Comment by aanersc** [comment]
@akorosov It is not fixed by that single line. That single line makes the table very long and we also loose that overflow ability of table. I need to read more about the `grid` in css. Solving it takes time!!!
