### ISSUE TITLE
Update catalog.model.Dataset structure for allowing external extention

### ISSUE THREAD

**Issue by korvinos** [nansencenter/django-geo-spaas#22]
### Description

Sometimes it would be great to have additional fields in the database. For example, it could be `polarization` and `pass` for SAR data, `drogue_lost_date` for SVP-drifters, etc. Unfortunately, there is only one loophole/(available ~empty field) in a current model structure which allows you to push an additional information/metadata. This field is `catalog.Dataset.summary`. But using this field for accumulating additional metadata is a messy and not convenient solution.

To keep a generic structure of the db ingester models is used just as a proxy. Thus it is not possible to add additional fields to an ingester model without creating a whole new table.

### Solution 

I did not find an entirely consistent solution, yet. But I thought that it could be possible to add one single field to the `catalog.models.Dataset` which will allow you to bind the Dataset with any other ("external") table/model from outside (from an ingester). Thus, the generic structure of the geo-spaas will not change but will allow to tune external tables and add additional metadata from ingesters

**Comment by akorosov** [comment]
The best solution is to extend the models by inheritance. In that case Django will automatically build another table with the additional fields only. The rest will be stored in the base table.:
``` python
class CustomDataset(catalog.models.Dataset):
    polarization = models.CharField(max_length=50, default='')
```
See also: https://docs.djangoproject.com/en/2.0/topics/db/models/#multi-table-inheritance
