### ISSUE TITLE
vagrant up fails

### ISSUE THREAD

**Issue by jeong1park** [nansencenter/django-geo-spaas#44]
It seems that migration fails, but still it is possible to connect to the virtual machine.
After login to the machine, the new environment should be activated manually by the command "source activate py3django".
If some python packages were not properly installed, add them to the list in the file, "provisioning/roles/nansencenter.django/tests/conda_env_requirements.yml"

TASK [geospaas : geospaas | Run migrate on django-geo-spaas project] ***********
fatal: [geospaas]: FAILED! => {"changed": false, "cmd": "./manage.py migrate --noinput --settings=project.settings --pythonpath=/vagrant/project", "msg": "\n:stderr: Traceback (most recent call last):\n  File \"./manage.py\", line 15, in <module>\n    execute_from_command_line(sys.argv)\n  File \"/home/vagrant/anaconda/envs/py3django/lib/python3.6/site-packages/django/core/management/__init__.py\", line 381, in execute_from_command_line\n    utility.execute()\n  File \"/home/vagrant/anaconda/envs/py3django/lib/python3.6/site-packages/django/core/management/__init__.py\", line 357, in execute\n    django.setup()\n  File \"/home/vagrant/anaconda/envs/py3django/lib/python3.6/site-packages/django/__init__.py\", line 24, in setup\n    apps.populate(settings.INSTALLED_APPS)\n  File \"/home/vagrant/anaconda/envs/py3django/lib/python3.6/site-packages/django/apps/registry.py\", line 112, in populate\n    app_config.import_models()\n  File \"/home/vagrant/anaconda/envs/py3django/lib/python3.6/site-packages/django/apps/config.py\", line 198, in import_models\n    self.models_module = import_module(models_module_name)\n  File \"/home/vagrant/anaconda/envs/py3django/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/vagrant/geospaas/nansat_ingestor/models.py\", line 4, in <module>\n    from geospaas.nansat_ingestor.managers import DatasetManager\n  File \"/vagrant/geospaas/nansat_ingestor/managers.py\", line 8, in <module>\n    from nansat.nansat import Nansat\n  File \"/home/vagrant/anaconda/envs/py3django/lib/python3.6/site-packages/nansat/__init__.py\", line 37, in <module>\n    from nansat.domain import Domain\n  File \"/home/vagrant/anaconda/envs/py3django/lib/python3.6/site-packages/nansat/domain.py\", line 23, in <module>\n    from nansat.tools import add_logger, initial_bearing, haversine, gdal, osr, ogr\n  File \"/home/vagrant/anaconda/envs/py3django/lib/python3.6/site-packages/nansat/tools.py\", line 31, in <module>\n    from mpl_toolkits.basemap import Basemap\n  File \"/home/vagrant/anaconda/envs/py3django/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py\", line 155, in <module>\n    pyproj_datadir = os.environ['PROJ_LIB']\n  File \"/home/vagrant/anaconda/envs/py3django/lib/python3.6/os.py\", line 669, in __getitem__\n    raise KeyError(key) from None\nKeyError: 'PROJ_LIB'\n", "path": "/home/vagrant/anaconda/envs/py3django/bin:/home/vagrant/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games", "state": "absent", "syspath": ["/tmp/ansible_django_manage_payload_jSeB5z/ansible_django_manage_payload.zip", "/vagrant", "/usr/lib/python2.7", "/usr/lib/python2.7/plat-x86_64-linux-gnu", "/usr/lib/python2.7/lib-tk", "/usr/lib/python2.7/lib-old", "/usr/lib/python2.7/lib-dynload", "/usr/local/lib/python2.7/dist-packages", "/usr/lib/python2.7/dist-packages"]}
	to retry, use: --limit @/vagrant/provisioning/site.retry

PLAY RECAP *********************************************************************
geospaas                   : ok=25   changed=2    unreachable=0    failed=1

**Comment by mortenwh** [comment]
I'll try to solve the issues with the vagrant configuration as follows:

- [ ] Activate conda env and migrate from ansible

- [ ] Activate conda env and add vocabularies from ansible

- [ ] Add localvm role

- [ ] Add folders and files to .gitignore

- [ ] Update wiki with information about how to install extra apps
