### ISSUE TITLE
pypi automation

### ISSUE THREAD

**Issue by azaf** [nansencenter/django-geo-spaas#75]

**Comment by azaf** [comment]
Dear @aperrin66 or Dear @akorosov please make the "PYPI_TOKEN" variable configured in the configuration of travis based on the nansen acount information in order to pass the tests for this project. I think this code is ready.

**Comment by akorosov** [comment]
Good job @azaf ! Thank you!!!

**Comment by azaf** [comment]
I hope to solve more bigger issues in this team with you and others :)
 @aperrin66  @akorosov
