### ISSUE TITLE
Several models have no uniqueness constraint

### ISSUE THREAD

**Issue by aperrin66** [nansencenter/django-geo-spaas#81]
### Problem

Several models, like Platform and Instrument, have no uniqueness constraint (a `natural_key()` method does not guarantee uniqueness of the object).

This makes them unsafe in a concurrency context, for example multi-threading. The following piece of code inserts three platforms instead of one:

```python
def create_platform():
    _, _ = geospaas.vocabularies.models.Platform.objects.get_or_create({
        'Category': 'test',
        'Series_Entity': 'test',
        'Short_Name': 'test',
        'Long_Name':'test'
    })

with concurrent.futures.ThreadPoolExecutor(max_workers=3) as executor:
    for i in range(3):
        executor.submit(create_platform)
```

The models I have found which are concerned by this issue are:
- all models in the `vocabularies` app
- `GeographicLocation`
- `Personnel`
- `Role`

#### Unique constraint
A pretty straightforward solution is to add a `unique=True` parameter on one of the fields, or a `unique_together` constraint in the Meta of the Model class. This would be the simplest solution to integrate with the existing model.

For the `vocabularies` models, we could do either of those:
- make `short_name`
- make long_name `long_name` unique
- put all or part of the attributes in a `unique_together` constraint

#### Make one field the primary key

This might be overkill and not really necessary since a primary key is automatically generated by Django.

**Comment by aperrin66** [comment]
@akorosov what do you think?

**Comment by akorosov** [comment]
Maybe we should rather add UniqueConstraint as suggested by Django Docs:
 https://docs.djangoproject.com/en/2.2/ref/models/constraints/#django.db.models.UniqueConstraint

It says unique_together may be deprecated in the future.

**Comment by aperrin66** [comment]
Yes, I saw this and I am currently setting it up with UniqueConstraints
