### ISSUE TITLE
relation between dataset and parameter table should be included in tests

### ISSUE THREAD

**Issue by aanersc** [nansencenter/django-geo-spaas#87]
There is a many to many relationship between dataset table and the parameter table. Some tests should be written in order to test the filtering ability of datasets based on specifying the parameters of them. This is working in the Django shell and the tests should assert that this filtering is ok. Thus, tests should consider below notes:
 - `ingest` or `ingest_thredds_crawl` command should be used to ingesting a new dataset with nansat 
 - we need to mock the `crawl` function for this purpose if `ingest_thredds_crawl` command is used
 - we need to mock the `Nansat` object 
 - assert that the filtering ability is working with such a command the assertion line of the test:
```python
ds = Dataset.objects.filter(parameters__standard_name='wind_speed')
```
 For this purpose, below python code ( *as snippet, not the exact code* ) can be used in a separate file:
```python
import os

import django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project.project.settings")
django.setup()

import geospaas.nansat_ingestor.management.commands.ingest as ingest
command = ingest.Command()
command.handle(files=["/data/MER_FRS_1PNPDK20120303_093810_000000333112_00180_52349_3561.N1"], nansat_option=[])



import geospaas.nansat_ingestor.management.commands.ingest_thredds_crawl as ingest_thredds_crawl
command = ingest_thredds_crawl.Command()
command.handle(url=["http://nbstds.met.no/thredds/catalog/NBS/S2A/2017/01/catalog.html"],date = '2017/01/10')
```

**Comment by akorosov** [comment]
- [ ] rename nansat_ingestor/management/commands/ingest_thredds_crawl.crawl to crawl_and_ingest


- [ ] Split nansat_ingestor/tests/tests.TestDatasetManager.test_getorcreate_localfile(self, mock_isfile) into three tests:
1. Test that get or create returns true and then false
2. Test that GLOBAL metadata is correct
3. Test that Parameter and DatasetParameter is added and searching by Parameter short_name (or standard_name) can be performed


- [ ] Add tests to nansat_ingestor/tests/tests. TestIngestThreddsCrawl__crawl__function which check that NansatDataset.objects.get_or_create() was called ONCE with correct values for url, uri_service_name and uri_service_type; AND checks that DatasetURI.objects.get_or_create was called (several times) with correct values of name, service, uri.

See Mock docs here:
https://docs.python.org/3/library/unittest.mock.html
