### ISSUE TITLE
issue in ingest_thredds_crawl when run from a test script with local database (not the test database)

### ISSUE THREAD

**Issue by aanersc** [nansencenter/django-geo-spaas#89]
when we want to create parameters for latitude the `get` command raise the `get() returned more than one Parameter -- it returned 2!` exception in this line:
https://github.com/nansencenter/django-geo-spaas/blob/f18160a7a2a8ae9175ce973be8b5124b78bf35b9/geospaas/nansat_ingestor/managers.py#L137

It is because we have several latitude parameter that we have in the installed database from the `build_container.sh` script which is run in the our database.

It is also good to check that the same problem is not occur in the `longitude` parameter as well.

**Comment by aperrin66** [comment]
These Parameter objects are inserted by the [update_vocabularies](https://github.com/nansencenter/django-geo-spaas/blob/master/geospaas/vocabularies/management/commands/update_vocabularies.py) command, which is executed  in the `build_container.sh` script.

There is probably an issue in this command which causes two Parameters with the same standard name to be inserted.

**Comment by akorosov** [comment]
I suggest that we exclude adding links to latitude and longitude as Parameter from Dataset.
It can be done e.g. in nansat_ingestor in the Manager

**Comment by aanersc** [comment]
solved by some modifications in the migration files of catalog by @aperrin66
