### ISSUE TITLE
Base viewer results are not paginated

### ISSUE THREAD

**Issue by aperrin66** [nansencenter/django-geo-spaas#98]
The list of datasets in the `base_viewer` app is not paginated, which will be a problem for large databases.
This is especially problematic, considering that all datasets are displayed when the page is first loaded.

**Comment by aanersc** [comment]
There is a specific function designed for the topic that you mentioned above:
https://github.com/nansencenter/django-geo-spaas/blob/be4a7316313fdb6974713a29478fa2a0250ba82c/geospaas/base_viewer/views.py#L34

**Comment by aanersc** [comment]
But it is not developed yet.

**Comment by aanersc** [comment]
@aperrin66 
What is your opinion, is it correctly designed and placed in this code?
